apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  type: NodePort
  selector:
    app: tomcat-deployment
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 32227
